CREATE DATABASE CODING_CHALLENGE

--CREATING TABLES
CREATE TABLE DEPARTMENT(
D_ID INT PRIMARY KEY,
D_Name VARCHAR(50))

CREATE TABLE EMPLOYEES(
E_ID INT PRIMARY KEY,
E_Name VARCHAR(50),
D_ID INT FOREIGN KEY REFERENCES DEPARTMENT(D_ID),
Salary INT,
Year_of_Experience INT
)
DROP TABLE EMPLOYEES
--INSERTING DATA
INSERT INTO DEPARTMENT VALUES
(1,'HR'),(2,'R&D'),(3,'PRODUCTION'),(4,'ACCOUNTS'),
(5,'MARKETING'),(6,'DESIGNING'),(7,'CLEANING')
INSERT INTO EMPLOYEES VALUES
(101,'JON SNOW',1,50000,5),(102,'AAEGON TARGAREON',2,100000,10),
(103,'SANSA STARK',6,40000,1),(104,'ARYA STARK',5,60000,2),
(105,'NED STARK',1,70000,7),(106,'JOFFERY',null,100,0),
(107,'CERSEI LANNISTER',7,5000,1),(108,'RAMSEY BOLTON',7,500,1),
(109,'ROBB STARK',1,50000,10),(110,'ROBERT BARATHEON',3,25000,10);

--1
--a. OVER AND PARTITION BY CLAUSE
SELECT E_ID,E_Name,
AVG(Salary) OVER() AS "OVERALL_AVERAGE_SALARY",
AVG(Salary) OVER (PARTITION BY D_ID) AS "AVERAGE_SALARY_BY_DEPARTMENT"
FROM EMPLOYEES
--b. CREATING SUB TOTALS
SELECT  D_ID, E_Name, SUM(Salary) FROM EMPLOYEES
GROUP BY ROLLUP(D_ID,E_Name)
--c. TOTAL AGGREGATIONS USING SQL QUERIES
--COUNT
SELECT COUNT(E_ID) AS TOTAL_EMPLOYEES FROM EMPLOYEES 
--SUM
SELECT D_ID, SUM(Salary)
FROM EMPLOYEES
GROUP BY D_ID
--AVG
SELECT D_ID,AVG(Salary) FROM EMPLOYEES
GROUP BY D_ID
--MAX
SELECT D_ID,MAX(Salary) AS MAX_SALARY_BY_DEPARTMENT
FROM EMPLOYEES
GROUP BY D_ID
--MIN
SELECT D_ID,MIN(Salary) AS MINIMUM_SALARY_BY_DEPARTMENT
FROM EMPLOYEES
GROUP BY D_ID
