CREATE DATABASE CODING_CHALLENGE

--CREATING TABLES
CREATE TABLE DEPARTMENT(
D_ID INT PRIMARY KEY,
D_Name VARCHAR(50))

CREATE TABLE EMPLOYEES(
E_ID INT PRIMARY KEY,
E_Name VARCHAR(50),
D_ID INT FOREIGN KEY REFERENCES DEPARTMENT(D_ID),
Salary INT,
Year_of_Experience INT
)
DROP TABLE EMPLOYEES
--INSERTING DATA
INSERT INTO DEPARTMENT VALUES
(1,'HR'),(2,'R&D'),(3,'PRODUCTION'),(4,'ACCOUNTS'),
(5,'MARKETING'),(6,'DESIGNING'),(7,'CLEANING')
INSERT INTO EMPLOYEES VALUES
(101,'JON SNOW',1,50000,5),(102,'AAEGON TARGAREON',2,100000,10),
(103,'SANSA STARK',6,40000,1),(104,'ARYA STARK',5,60000,2),
(105,'NED STARK',1,70000,7),(106,'JOFFERY',null,100,0),
(107,'CERSEI LANNISTER',7,5000,1),(108,'RAMSEY BOLTON',7,500,1),
(109,'ROBB STARK',1,50000,10),(110,'ROBERT BARATHEON',3,25000,10);


--2 JOINS
--NATURAL JOIN
SELECT * FROM EMPLOYEES AS E 
JOIN DEPARTMENT AS D ON D.D_ID=E.D_ID
--INNER JOIN
SELECT * FROM EMPLOYEES AS E
INNER JOIN DEPARTMENT AS D ON E.D_ID=D.D_ID
--LEFT JOIN
SELECT * FROM EMPLOYEES AS E
LEFT JOIN DEPARTMENT AS D ON E.D_ID=D.D_ID
--RIGHT JOIN
SELECT * FROM EMPLOYEES AS E
RIGHT JOIN DEPARTMENT AS D ON E.D_ID=D.D_ID
--FULL OUTER JOIN
SELECT * FROM EMPLOYEES AS E
FULL OUTER JOIN DEPARTMENT AS D ON E.D_ID=D.D_ID
--CROSS JOIN
SELECT * FROM EMPLOYEES 
CROSS JOIN DEPARTMENT